name: Deploy to yohann-caby.fr

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]
  workflow_dispatch:
    

env:
  FTP_HOST : ${{ secrets.FTP_HOST }}
  FTP_USER : ${{ secrets.FTP_USER }}
  FTP_PWD : ${{ secrets.FTP_PWD }}

jobs:
  build:
    runs-on : ubuntu-latest

    steps:
      - name: Environement
        run: | 
          echo $FTP_HOST  
          echo $FTP_USER
    
