name: Deploy to yohann-caby.fr

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]
  workflow_dispatch:

jobs:
  build:
    runs-on : ubuntu-latest

    steps:
      - name: Environement
        run: | 
          echo ${{ secrets.FTP_HOST }}
          echo ${{ secrets.FTP_USER }}

    
