name: Deploy to yohann-caby.fr

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]
  workflow_dispatch:
env:
  FTP_HOST: ${{ secrets.FTP_HOST }}
jobs:
  build:
    runs-on : ubuntu-latest

    steps:
      - name: Environement
        run: | 
          echo ${FTP_HOST}
          echo ${{ secrets.FTP_USER }}

    
